// src/pages/Home.svelte
<div class="row">
	<div class="col-lg-12">
		<div class="card card-block card-stretch card-transparent">
			<div class="card-header d-flex justify-content-between pb-0">
				<div class="header-title">
					<h4 class="card-title">Files</h4>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12">
		<div
			class="card card-block c
		ard-stretch card-height"
		>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table mb-0 table-borderless tbl-server-info">
						<thead>
							<tr>
								<th scope="col">Name</th>
								<th scope="col">Owner</th>
								<th scope="col">Last Edit</th>
								<th scope="col">File Size</th>
								<th scope="col" />
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="icon-small bg-danger rounded mr-3">
											<i class="ri-file-excel-line" />
										</div>
										<div
											data-load-file="file"
											data-load-target="#resolte-contaniner"
											data-url="../assets/vendor/doc-viewer/files/demo.pdf"
											data-toggle="modal"
											data-target="#exampleModal"
											data-title="alexa5.pdf"
											style="cursor: pointer;"
										>
											Weekly Report.pdf
										</div>
									</div>
								</td>
								<td>Me</td>
								<td>Mar 30, 2020 Gail Forcewind</td>
								<td>10 MB</td>
								<td>
									<div class="dropdown">
										<span
											class="dropdown-toggle"
											id="dropdownMenuButton10"
											data-toggle="dropdown"
										>
											<i class="ri-more-fill" />
										</span>
										<div
											class="dropdown-menu dropdown-menu-right"
											aria-labelledby="dropdownMenuButton10"
										>
											<a class="dropdown-item" href="#"
												><i class="ri-eye-fill mr-2" />View</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-delete-bin-6-fill mr-2" />Delete</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-pencil-fill mr-2" />Edit</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-printer-fill mr-2" />Print</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-file-download-fill mr-2" />Download</a
											>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="icon-small bg-primary rounded mr-3">
											<i class="ri-file-download-line" />
										</div>
										<div
											data-load-file="file"
											data-load-target="#resolte-contaniner"
											data-url="../assets/vendor/doc-viewer/files/demo.docx"
											data-toggle="modal"
											data-target="#exampleModal"
											data-title="alexa6.docx"
											style="cursor: pointer;"
										>
											Milestone.docx
										</div>
									</div>
								</td>
								<td>Penny</td>
								<td>Mar 31, 2020 Penny</td>
								<td>65 MB</td>
								<td>
									<div class="dropdown">
										<span
											class="dropdown-toggle"
											id="dropdownMenuButton11"
											data-toggle="dropdown"
										>
											<i class="ri-more-fill" />
										</span>
										<div
											class="dropdown-menu dropdown-menu-right"
											aria-labelledby="dropdownMenuButton11"
										>
											<a class="dropdown-item" href="#"
												><i class="ri-eye-fill mr-2" />View</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-delete-bin-6-fill mr-2" />Delete</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-pencil-fill mr-2" />Edit</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-printer-fill mr-2" />Print</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-file-download-fill mr-2" />Download</a
											>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="icon-small bg-info rounded mr-3">
											<i class="ri-file-excel-line" />
										</div>
										<div
											data-title="Alexa8.xlsx"
											data-load-file="file"
											data-load-target="#resolte-contaniner"
											data-url="../assets/vendor/doc-viewer/files/demo.xlsx"
											data-toggle="modal"
											data-target="#exampleModal"
											style="cursor: pointer;"
										>
											Training center.xlsx
										</div>
									</div>
								</td>
								<td>Banny</td>
								<td>Mar 30, 2020 Banny</td>
								<td>90 MB</td>
								<td>
									<div class="dropdown">
										<span
											class="dropdown-toggle"
											id="dropdownMenuButton13"
											data-toggle="dropdown"
										>
											<i class="ri-more-fill" />
										</span>
										<div
											class="dropdown-menu dropdown-menu-right"
											aria-labelledby="dropdownMenuButton13"
										>
											<a class="dropdown-item" href="#"
												><i class="ri-eye-fill mr-2" />View</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-delete-bin-6-fill mr-2" />Delete</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-pencil-fill mr-2" />Edit</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-printer-fill mr-2" />Print</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-file-download-fill mr-2" />Download</a
											>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="icon-small bg-success rounded mr-3">
											<i class="ri-file-excel-line" />
										</div>
										<div
											data-load-file="file"
											data-load-target="#resolte-contaniner"
											data-url="../assets/vendor/doc-viewer/files/demo.docx"
											data-toggle="modal"
											data-target="#exampleModal"
											data-title="alexa7.pptx"
											style="cursor: pointer;"
										>
											Training center.pptx
										</div>
									</div>
								</td>
								<td>Me</td>
								<td>Apr 04, 2020 me</td>
								<td>10 MB</td>
								<td>
									<div class="dropdown">
										<span
											class="dropdown-toggle"
											id="dropdownMenuButton12"
											data-toggle="dropdown"
										>
											<i class="ri-more-fill" />
										</span>
										<div
											class="dropdown-menu dropdown-menu-right"
											aria-labelledby="dropdownMenuButton12"
										>
											<a class="dropdown-item" href="#"
												><i class="ri-eye-fill mr-2" />View</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-delete-bin-6-fill mr-2" />Delete</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-pencil-fill mr-2" />Edit</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-printer-fill mr-2" />Print</a
											>
											<a class="dropdown-item" href="#"
												><i class="ri-file-download-fill mr-2" />Download</a
											>
										</div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

// src/pages/Home.tsx
import React from 'react';
import FileTableItem from '../components/FileTableItem';
import { AppContext } from '../context/AppContext';
import DefaultLayout from '../layouts/DefaultLayout';

interface HomePageProps {}

const HomePage: React.FC<HomePageProps> = () => {
	const { files } = React.useContext(AppContext);

	return (
		<DefaultLayout>
			<div className='row'>
				<div className='col-lg-12'>
					<div className='card card-block card-stretch card-transparent'>
						<div className='card-header d-flex justify-content-between pb-0'>
							<div className='header-title'>
								<h4 className='card-title'>Files</h4>
							</div>
						</div>
					</div>
				</div>
				<div className='col-lg-12'>
					<div
						className='card card-block c
		ard-stretch card-height'>
						<div className='card-body'>
							<div className='table-responsive'>
								<table className='table mb-0 table-borderless tbl-server-info'>
									<thead>
										<tr>
											<th scope='col'>Name</th>
											<th scope='col'>ID</th>
											<th scope='col'>Description</th>
											<th scope='col'>Type</th>
											<th scope='col'>File Size</th>
											<th scope='col'>Uploader</th>``
											<th scope='col' />
										</tr>
									</thead>
									<tbody>
										{files?.map((file: any, i: number) => {
											const vals = ['', 'primary', 'success', 'info', 'danger'];
											const rndInt = Math.floor(Math.random() * 4) + 1;
											return (
												<FileTableItem
													file={file}
													color={vals[rndInt] as any}
													key={i}
												/>
											);
										})}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</DefaultLayout>
	);
};

export default HomePage;
